//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public double CountInPack { get; set; }
        public string Unit { get; set; }
        public Nullable<double> CountInStock { get; set; }
        public double MinCount { get; set; }
        public string Description { get; set; }
        public int Cost { get; set; }
        public string Image { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
    }
}
